server:
  port: ${PORT:7001} #服务端口  ${PORT:7001} 标识 可以启动传入端口号 如果不传入 默认7002
spring:
  application:
    name: eureka-center #应用示例的主机名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果 不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://eureka02:7002/eureka/} # ${EUREKA_SERVER:http://eureka02:7002/eureka/} 表示地址可以启动的是传入EUREKA_SERVER一个地址 如果不传入 默认为 后面的地址
    server:
      enable‐self‐preservation: false #是否开启自我保护模式
      eviction‐interval‐timer‐in‐ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
    instance:
      hostname: ${EUREKA_DOMAIN:eureka01}  #当前的eureka服务名
