server:
  port: 9002 #服务的端口
spring:
  application:
    name: eureka-ribbon-service #应用示例的主机名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果 不配置则默认本机8761端口）
      defaultZone: http://localhost:7000/eureka/
