server:
  port: 6001 #服务的端口
spring:
  application:
    name: eureka-ribbon-client-one #应用示例的主机名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果 不配置则默认本机8761端口）
      defaultZone: http://localhost:7000/eureka/

ribbon:
  maxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  maxAutoRetriesNextServer: 3 #切换实例的重试次数
  okToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作 没有实现幂等的情况下是很危险的,所以设置为false
  connectTimeout: 5000 #请求连接的超时时间
  readTimeout: 6000 #请求处理的超时时间
